version: "3.7"
x-common-environment: &common-env
  - POSTGRES_HOST=postgres
  - POSTGRES_PORT=5432
  - POSTGRES_USER=user
  - POSTGRES_PASSWORD=password
  - POSTGRES_DB=account
  - POSTGRES_LOGGING=true
  - POSTGRES_SYNCHRONIZE=true
  - REDIS_HOST=redis
  - REDIS_PORT=6379
  - REDIS_PASSWORD=password
  - REDIS_TTL=5000

services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./volumes/redis:/data

  postgres:
    container_name: postgres-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: "account"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"   
    ports:
      - 5444:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d account"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./volumes/postgres_init:/docker-entrypoint-initdb.d
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - '5055:80'
    volumes:
      - ./volumes/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - backend

  minio:
    image: minio/minio:latest
    container_name: minio-storage
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ozontech
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./volumes/minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./volumes/zookeeper:/var/lib/zookeeper
    networks:
      - "backend"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: "kafka"
    restart: unless-stopped
    ports:
      - '9092:9092'
    networks:
      - "backend"
    volumes:
      - ./volumes/kafka:/opt/bitnami/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: 'PLAINTEXT://:29092,PLAINTEXT_HOST://:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.3.0
    hostname: control-center
    restart: unless-stopped
    container_name: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    networks:
      - "backend"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  # account:
  #   build:
  #     context: .
  #     dockerfile: ./apps/account/Dockerfile
  #   restart: always
  #   command: yarn dev-account
  #   container_name: account_container
  #   environment:
  #     &common-env
  #     - HTTP_PORT=3030
  #     - KAFKA_BROKER=kafka:9092

  #     - JWT_ACCESS_SECRET=asdfasffqw12
  #     - JWT_ACCESS_EXPIRES='1d'
  #     - JWT_REFRESH_SECRET=sdva121fafaw
  #     - JWT_REFRESH_EXPIRES='30d'
  #   ports:
  #     - '3031:3030'
  #     - '4030:4030'
  #   volumes:
  #     - .:/opt/src/app
  #   depends_on:
  #     - postgres
  #     - kafka
  #     - redis
  #   networks:
  #     - backend

  # gateway:
  #   build:
  #     context: .
  #     dockerfile: ./apps/gateway/Dockerfile
  #   restart: always
  #   command: yarn dev-gateway
  #   container_name: gateway_container
  #   environment:
  #     - PORT=3004
  #     - KAFKA_BROKER=kafka:9092
  #     - X_API_KEY=47733ca1-3694-410c-8656-0f6178d60dd9

  #     - JWT_ACCESS_SECRET=asdfasffqw12
  #     - JWT_ACCESS_EXPIRES='1d'

  #     - ACCOUNT_GRAPHQL_URL=http://account:3030
  #     - ACCOUNT_HOST=account
  #     - ACCOUNT_PORT=4030

  #   ports:
  #     - '3005:3004'
  #   volumes:
  #     - .:/opt/src/app
  #   depends_on:
  #     - postgres
  #     - kafka
  #     - account
  #   networks:
  #     - backend



volumes:
  postgres_data:
  pgadmin-data:

networks:
  backend:
    driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 10.5.0.0/16
    #       ip_range: 10.5.0.0/24
    #       gateway: 10.5.0.1
    #       aux_addresses:
    #         kafka: 10.5.0.2
    #         zookeeper: 10.5.0.3
