version: "3"
services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: yarn dev-reservations
    ports:
      - '7001:7001'
    volumes:
      - .:/opt/src/app
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volumes/data:/data/db
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn dev-auth
    ports:
      - '4001:4001'
      - '4002:4002'
    volumes:
      - .:/opt/src/app
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: yarn dev-payments
    ports:
      - '5002:5002'
    volumes:
      - .:/opt/src/app
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: yarn dev-notifications
    ports:
      - '6002:6002'
    volumes:
      - .:/opt/src/app
